default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: kursach_development

test:
  <<: *default
  database: kursach_test

production:
  primary: &primary_production
    <<: *default
    database: kursach_production
    username: kursach
    password: <%= ENV["KURSACH_DATABASE_PASSWORD"] %>